apiVersion: v1
kind: Service
metadata:
  name: myrecipe-backend
spec:
  type: ClusterIP
  selector:
    app: myrecipe-backend
  ports:
    - name: http
      port: 8080          # クラスタ内のServiceポート
      targetPort: 8080     # Podのコンテナポート