apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  API_BASE_URL: "http://192.168.3.17:30080/api/recipes"
  API_GET_RECIPES_URL: "http://192.168.3.17:30080/api/recipes/by-category"
